pipeline {
    agent any
    environment {
        REPORT_EMAIL = sh(returnStdout: true, script:'echo -n ${BUILD_USER_EMAIL:-ghislain.bernard@gmail.com}')
    }
    options {
        skipDefaultCheckout()
        timeout(unit: 'MINUTES', time: 5)
    }
    stages {
        stage('clean') {
            steps {
                cleanWs()
            }
        }
        stage('clone') {
            steps {
                checkout scm
            }
        }
        stage('build') {
            steps {
                sh 'env | sort'
                sh 'echo "${REPORT_EMAIL}"'
                sshagent(credentials: ['jenkins.homeware.ovh']) {
                    withCredentials([string(credentialsId: 'borg.homeware.ovh', variable: 'BORG_PASSPHRASE')]) {
                        sh 'ssh user@lausanne.homeware.ovh hostnamectl hostname'
                        sh 'ssh user@lausanne.homeware.ovh unbuffer sudo BORG_PASSPHRASE=$BORG_PASSPHRASE \
                        bash /opt/jenkins/${JOB_NAME}.sh'
                    }
                }
            }
        }
    }
    post {
        aborted {
            mail body: "ABORTED\n\n${BUILD_URL}", subject: "${JOB_NAME}#${BUILD_NUMBER} [FAILURE]",
                to: "$REPORT_EMAIL"
        }
        failure {
            mail body: "FAILURE\n\n${BUILD_URL}", subject: "${JOB_NAME}#${BUILD_NUMBER} [FAILURE]",
                to: "$REPORT_EMAIL"
        }
    }
}
